### ISSUE TITLE
Rewrite to active record graphql?

### ISSUE THREAD

**Issue by emilebosch** [gauravtiwari/apollo_on_rails#1]
Heya, i just wanted to give you a heads up. You seem to be a fore runner with graphql and rails. Have you seen this? 

Automatic mapping to your rails https://github.com/goco-inc/graphql-activerecord?

**Comment by gauravtiwari** [comment]
Hey @emilebosch 

Thanks for the heads up :) No, I haven't, but it's looking interesting. I will try it out this week and update the repo :)
